version: '2'
services:
    jblog1-app:
        image: jblog1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jblog1-mysql:3306/jblog1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jblog1-mysql:
        extends:
            file: mysql.yml
            service: jblog1-mysql
